apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: demo-github-2
spec:
  activeCommitStatuses:
  # The ArgoCDCommitStatus CR will maintain this commit status based on the application health.
  - key: argocd-health
  environments:
    - autoMerge: true
      branch: environment/development-2
    - autoMerge: true
      branch: environment/staging-2
    - autoMerge: false
      branch: environment/prod-2
  gitRepositoryRef:
    name: gitops-promoter-demo-repo
