apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: gitops-promoter-demo-repo
spec:
  github:
    name: gitops-promoter-examples
    owner: crenshaw-dev
  scmProviderRef:
    name: gitops-promoter-demo-scm
